import py_compile as c
import sys

def compile_tests(d):
    c.compile(d + "/attr.py", "attr.pyc")
    c.compile(d + "/church.py", "church.pyc")
    c.compile(d + "/closure.py", "closure.pyc")
    c.compile(d + "/CMakeLists.txt", "CMakeLists.txtc")
    c.compile(d + "/dict_view.py", "dict_view.pyc")
    c.compile(d + "/emro.py", "emro.pyc")
    c.compile(d + "/fib.py", "fib.pyc")
    c.compile(d + "/func.py", "func.pyc")
    c.compile(d + "/gc.py", "gc.pyc")
    c.compile(d + "/make_func.py", "make_func.pyc")
    c.compile(d + "/mro.py", "mro.pyc")
    c.compile(d + "/oom.py", "oom.pyc")
    c.compile(d + "/op.py", "op.pyc")
    c.compile(d + "/st_attr.py", "st_attr.pyc")
    c.compile(d + "/subscr.py", "subscr.pyc")
    c.compile(d + "/test_all.py", "test_all.pyc")
    c.compile(d + "/test_builtin.py", "test_builtin.pyc")
    c.compile(d + "/test_class.py", "test_class.pyc")
    c.compile(d + "/test_closure.py", "test_closure.pyc")
    c.compile(d + "/test_default.py", "test_default.pyc")
    c.compile(d + "/test_dict.py", "test_dict.pyc")
    c.compile(d + "/test_for.py", "test_for.pyc")
    c.compile(d + "/test_func.py", "test_func.pyc")
    c.compile(d + "/test_if.py", "test_if.pyc")
    c.compile(d + "/test_len.py", "test_len.pyc")
    c.compile(d + "/test_list.py", "test_list.pyc")
    c.compile(d + "/test_param.py", "test_param.pyc")
    c.compile(d + "/test_ret.py", "test_ret.pyc")
    c.compile(d + "/test_sort.py", "test_sort.pyc")
    c.compile(d + "/test_string.py", "test_string.pyc")
    c.compile(d + "/test_token.txt", "test_token.txtc")
    c.compile(d + "/test_type.py", "test_type.pyc")
    c.compile(d + "/test_var.py", "test_var.pyc")
    c.compile(d + "/test_while.py", "test_while.pyc")
    c.compile(d + "/timpt.py", "timpt.pyc")
    c.compile(d + "/tsum.py", "tsum.pyc")
    c.compile(d + "/vec.py", "vec.pyc")
    c.compile(d + "/alltest.py", "alltest.pyc")

if __name__ == "__main__":
    compile_tests(sys.argv[1])

